---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  packages: read
  security-events: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/app-ci.yaml@3bd4082539091854a3efb431d545f6b01399589a # v1.0.11
