---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pull-requests: read
  packages: read
  security-events: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/app-ci.yaml@6e107bbfcc7007ffc686df8999a3dde510f8c251 # v2.0.2
