---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/labels.yaml@6e107bbfcc7007ffc686df8999a3dde510f8c251 # v2.0.2
