---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/labels.yaml@33268deb018d8496ffbdb76e6da9219cebd22d50 # v1.1.0
