---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/pr-labels.yaml@3bd4082539091854a3efb431d545f6b01399589a # v1.0.11
