---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/pr-labels.yaml@33268deb018d8496ffbdb76e6da9219cebd22d50 # v1.1.0
