---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/pr-labels.yaml@6e107bbfcc7007ffc686df8999a3dde510f8c251 # v2.0.2
