---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/release-drafter.yaml@33268deb018d8496ffbdb76e6da9219cebd22d50 # v1.1.0
