---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/release-drafter.yaml@3bd4082539091854a3efb431d545f6b01399589a # v1.0.11
